### ISSUE TITLE
`AIMLchatting/aaa/*.aiml`这些文件里的模板是您自己翻译的吗？

### ISSUE THREAD

**Issue by tvytlx** [sxhfut/AIMLchatting#1]
我也写了一个类似AIML的程序，需要一些对话语料，您有什么建议吗？

**Comment by tvytlx** [comment]
似乎没有啥办法，要么手写，要么用别人的。

**Comment by sxhfut** [comment]
这个实际上是一个aiml的核心了，只能自己整理，我之前尝试着从alice的语料中翻译，但是效果不好。
